<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.triggers.TimerTrigger_-TimerTriggerCause/>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <hudson.plugins.sitemonitor.SiteMonitorRootAction plugin="sitemonitor@0.6">
      <mResults>
        <hudson.plugins.sitemonitor.model.Result>
          <mSite>
            <mUrl>http://127.0.0.1:8081/IgalNisanDanielNissim/</mUrl>
            <timeout>30</timeout>
            <successResponseCodes/>
            <admitInsecureSslCerts>false</admitInsecureSslCerts>
          </mSite>
          <mStatus>EXCEPTION</mStatus>
          <mNote>[EXCEPTION] java.net.ConnectException: Connection refused (Connection refused) - Connection refused (Connection refused)</mNote>
        </hudson.plugins.sitemonitor.model.Result>
      </mResults>
    </hudson.plugins.sitemonitor.SiteMonitorRootAction>
    <hudson.tasks.MailMessageIdAction plugin="mailer@438.v02c7f0a_12fa_4">
      <messageId>&lt;214454832.4.1673956380652@aa68dddb744f&gt;</messageId>
    </hudson.tasks.MailMessageIdAction>
  </actions>
  <queueId>163</queueId>
  <timestamp>1673956380490</timestamp>
  <startTime>1673956380520</startTime>
  <result>FAILURE</result>
  <duration>1931</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/jenkins_home/workspace/monitoring</workspace>
  <hudsonVersion>2.375</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="java.util.Collections$UnmodifiableSet">
    <c class="sorted-set"/>
  </culprits>
</build>